### ISSUE TITLE
 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:8050/api/v1/conversations. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 403.

### ISSUE THREAD

**Issue by CE1CECL** [fossteams/fossteams-frontend#2]
in Firefox

 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:8050/api/v1/conversations. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 403.

**Comment by denysvitali** [comment]
What do you see in the server logs?

Can you get the conversations by visiting the page directly?

**Comment by CE1CECL** [comment]
> What do you see in the server logs?
> 
> Can you get the conversations by visiting the page directly?

I can go to it directly
its the browser that isn't allowing localhost:8050 b/c of CORS, which usually gets fixed with an extension or other
happens in chrome too

**Comment by denysvitali** [comment]
Oh I see your issue.
You're visiting http://localhost:8080 instead of http://127.0.0.1:8080

CORS on the backend is configured to only allow request from 127.0.0.1:8080, see here:
https://github.com/fossteams/fossteams-backend/blob/master/internal/server/server.go#L333

**Comment by CE1CECL** [comment]
> Oh I see your issue. You're visiting http://localhost:8080 instead of http://127.0.0.1:8080
> 
> CORS on the backend is configured to only allow request from 127.0.0.1:8080, see here: https://github.com/fossteams/fossteams-backend/blob/master/internal/server/server.go#L333

 WARNING  Compiled with 2 warnings                                                                            7:53:47 AM

 warning  in ./node_modules/vue-property-decorator/lib/index.js

"export 'default' (reexported as 'Component') was not found in 'vue-class-component'

 warning  in ./node_modules/vue-property-decorator/lib/index.js

"export 'default' (reexported as 'Vue') was not found in 'vue'


  App running at:
  - Local:   http://localhost:8081/
  - Network: http://192.168.1.234:8081/

  Note that the development build is not optimized.
  To create a production build, run yarn build.

Issues checking in progress...
No issues found.


:8080?? i got :8081 (8080 is in use maybe?)

**Comment by CE1CECL** [comment]
> > Oh I see your issue. You're visiting http://localhost:8080 instead of http://127.0.0.1:8080
> > CORS on the backend is configured to only allow request from 127.0.0.1:8080, see here: https://github.com/fossteams/fossteams-backend/blob/master/internal/server/server.go#L333
> 
> WARNING Compiled with 2 warnings 7:53:47 AM
> 
> warning in ./node_modules/vue-property-decorator/lib/index.js
> 
> "export 'default' (reexported as 'Component') was not found in 'vue-class-component'
> 
> warning in ./node_modules/vue-property-decorator/lib/index.js
> 
> "export 'default' (reexported as 'Vue') was not found in 'vue'
> 
> App running at:
> 
>     * Local:   http://localhost:8081/
> 
>     * Network: http://192.168.1.234:8081/
> 
> 
> Note that the development build is not optimized. To create a production build, run yarn build.
> 
> Issues checking in progress... No issues found.
> 
> :8080?? i got :8081 (8080 is in use maybe?)

in chrome console

Access to XMLHttpRequest at 'http://127.0.0.1:8050/api/v1/conversations' from origin 'http://127.0.0.1:8081' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
